str2="Con la patente di categoria A si possono condurre anche i tricicli di potenza superiore a 15 kW, qualunque sia l'età del conducente"
str1="Con lo potente ol cotegono A sl possono conourre onche l tnclcl ol potenzo supenore ol5 KW,quolunque sloleto oel conoucente"
      
def remove_single_quotes(input_string):
    return (input_string
            .replace("() ", "")
            .replace('  ', ' ')
            .replace('- ', '')
            .replace('-', '')
            .replace('.', '')
            .replace(', ', ',')
            .replace("’i", '')
            .replace("'i", "")
            .replace("‘i", "")
            .replace("E ", 'E')
            .replace("È", 'E')
            .replace("’ ", '')
            .replace("’", '')
            .replace("' ", "")
            .replace("'", "")
            .replace("‘ ", "")
            .replace("‘", "")
            .replace('“', '"')
            .replace('N', 'V')
            .replace('i', 'l')
            .replace('f', 'l')
            .replace('1', 'l')
            .replace('I', 'l')
            .replace('[', 'l')
            .replace(']', 'l')
            .replace('{', 'l')
            .replace('(', 'l')
            .replace('}', 'l')
            .replace(')', 'l')
            .replace('!', 'l')
            .replace('|', 'l')
            .replace('U', 'l')
            .replace('L', 'l')
            .replace('é', 'e')
            .replace('K', 'k')
            .replace('è', 'e')
            .replace('j', 'o')
            .replace('à', 'o')
            .replace('a', 'o')
            .replace('ù', 'o')
	          .replace('&', 'o')
            .replace('€', 'o')
            .replace('d', 'o')
            .replace('ò', 'o')
            .replace('0', 'o')
            .replace('rl', 'n')
            .replace('nl', 'n')
            .replace('ul', 'u')
            .replace('5 t', '5t')
            .replace('T e', 'Te')
            .replace('o l', 'ol')
            .replace('l s', 'ls')
            .replace('l v', 'lv')
            .replace('l m', 'm')
            .replace('ll', 'l')
            .replace(' } ', ' '))

def main_process():
    extract=remove_single_quotes(str2)
    if(str1 == extract):
        print("Perfect!!!")
    else:
        print("Sorry, no match", "\n", str1, "\n", extract)
        
main_process()
